name: 'elements'
version: 0.0.1
description: Collection of polymer.dart elements.
author: Andrea Cantafio
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: '>=0.10.0 <0.11.0'
  kk4r1m:
    git: https://github.com/k4rr1m/kk4r1m
  paper_elements: '>=0.7.0 <0.8.0'
  path: any
  polymer: '>=0.16.0 <0.17.0'
  stylus: any
transformers:
- polymer:
    entry_points: web/index.html
